---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ the_hive_service_name }}'
    consul_services:
      - name: '{{ the_hive_service_name }}'
        tags: ['thehive', 'incidents', 'security']
        port: '{{ the_hive_port }}'
        address: '{{ ansible_local.tinc.vpn_ip }}'
        checks:
          - id: '{{ the_hive_service_name }}-health'
            name: Cassandra Healthcheck
            type: http
            http: 'http://localhost:{{ the_hive_port }}/'
