---
- name: Install Java OpenJRE
  apt:
    name: openjdk-11-jre-headless

- name: Make sure we are using Java 11
  alternatives:
    name: 'java'
    path: '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'

- name: Create service group
  group:
    name: '{{ the_hive_service_user }}'

- name: Create service user
  user:
    name: '{{ the_hive_service_user }}'
    group: '{{ the_hive_service_user }}'

- name: Check if already installed
  stat:
    path: '/opt/thehive4-{{ the_hive_version }}'
  register: the_hive_symlink

- name: Download binary release zip
  get_url:
    url: '{{ the_hive_binary_url }}'
    dest: '/tmp/thehive4.zip'
    checksum: 'md5:{{ the_hive_binary_md5 }}'
    mode: 0644
  when: not the_hive_symlink.stat.exists

- name: Unpack binary release zip
  unarchive:
    src: '/tmp/thehive4.zip'
    dest: '/opt'
    group: '{{ the_hive_service_user }}'
    mode: 0755
    remote_src: true
    creates: /opt/thehive4-{{ the_hive_version }}/bin/thehive
  when: not the_hive_symlink.stat.exists

- name: Symlinks specific version
  file:
    src: '/opt/thehive4-{{ the_hive_version }}'
    dest: '{{ the_hive_install_path }}'
    state: 'link'

- name: Remove binary release zip
  file:
    path: '/tmp/thehive4.zip'
    state: absent
