---
cortex_service_name: 'cortex'
cortex_service_user: 'cortex'

# Download
cortex_version: '3.1.0-1'
cortex_binary_url: 'https://download.thehive-project.org/cortex-{{ cortex_version }}.zip'
cortex_binary_md5: 'd60ba933de59362c1ed2a7631b2a20f9'

# Database
# WARNING: Name changes with versions!
cortex_index_name: 'cortex_4'

# Paths
cortex_install_path: '/opt/{{ cortex_service_name }}'
cortex_conf_path: '/etc/cortex'
cortex_logs_path: '/var/log/cortex'

# Logging level: info/verbose/debug
cortex_logs_level: 'info'

# Ports
cortex_port: 9001

# ElasticSearch cluster nodes
cortex_search_index: 'cortex'
cortex_search_nodes: []
#  - { name: "node-01", addr: "10.1.2.3", port: 1234 }

# Secret for cookies and built-in encryption
cortex_http_secret: ~

# Super Admin user
cortex_admin_user: 'admin'
cortex_admin_pass: ~

# Organization
cortex_org_name: 'Status.im'

# User for TheHive API access
cortex_the_hive_user: 'thehive'
cortex_the_hive_pass: ~
