---
# Root password
bootstrap__root_pass: '{{lookup("bitwarden", "root-pass")}}'
# Consul encryption key and ACL token
bootstrap__consul_encryption_key: '{{lookup("bitwarden", "consul", field="encryption-key")}}'
bootstarp__consul_agent_acl_token: '{{lookup("bitwarden", "consul", field="agent-acl-token")}}'

# CloudFlare Origin certificates
origin_certs:
  - domain: 'status.im'
    crt: '{{lookup("bitwarden", "Cloudflare/status.im", file="origin.crt")}}'
    key: '{{lookup("bitwarden", "Cloudflare/status.im", file="origin.key")}}'
    default: true

# 8GB to match RAM
swap_file_size_mb: 8192

# Consul Catalog API
consul_catalog_url: 'http://localhost:8500/v1/catalog'

# general container config
cont_state: started
cont_recreate: false
cont_restart: false
