---
# general container config
cont_state: started
cont_recreate: false
cont_restart: false

# 8GB to match RAM
swap_file_size_mb: 8192

# CloudFlare Origin certificates
origin_certs:
  - domain: 'status.im'
    crt: '{{lookup("passwordstore", "cloud/Cloudflare/status.im/origin.crt returnall=true")}}'
    key: '{{lookup("passwordstore", "cloud/Cloudflare/status.im/origin.key returnall=true")}}'
    default: true

# Root password
bootstrap__root_pass: '{{lookup("passwordstore", "hosts/admin-pass")}}'

# Consul Encryption
consul_encryption_key: '{{lookup("passwordstore", "services/consul/encryption-key")}}'

# Consul Catalog API
consul_catalog_url: 'http://localhost:8500/v1/catalog'
