---
# Cassandra cluster for storing metrics
cassandra_cluster_name: 'thp'
cassandra_data_dir: '/data/cassandra'
cassandra_rpc_address: '{{ ansible_local.wireguard.vpn_ip }}'
cassandra_listen_address: '{{ ansible_local.wireguard.vpn_ip }}'
cassandra_storage_port: 7000
cassandra_native_port: 9042
cassandra_exp_listen_port: 8080
cassandra_db_users:
  - user: '{{ lookup("bitwarden", "the-hive/cassandra", field="username") }}'
    pass: '{{ lookup("bitwarden", "the-hive/cassandra", field="password") }}'

# ElasticSearch Cluster
es_cluster_name: 'cortex'
es_cont_name: elasticsearch
es_api_port: 9200
es_node_port: 9300
es_metrics_cont_port: 9114

# WARNING: This works only if playbook is ran for whole group
es_master_nodes: |
  {{ ansible_play_hosts
   | map('extract', hostvars)
   | list
   | json_query(
   '[].{
     name: hostname,
     addr: ansible_local.wireguard.vpn_ip,
     port: to_string(es_node_port)
   }') }}

# Since Logstash stores 1 index per day this is fine
# See: https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster
es_number_of_replicas: 1
es_number_of_shards: 3

# JVM memory settings
es_jvm_mem_ratio: 0.5
es_jvm_mem: '{{ (ansible_memtotal_mb * es_jvm_mem_ratio) | round(0, "floor") }}'
es_jvm_min_heap: '{{ es_jvm_mem | int }}m'
es_jvm_max_heap: '{{ es_jvm_mem | int }}m'

# ElasticHQ connects to the local container
es_hq_lb_cont_name: '{{ es_cont_name }}'

# oauth access
oauth_domain: 'thehive-es.infra.status.im'
oauth_cont_name: '{{ es_hq_cont_name }}-oauth'
oauth_upstream_cont: '{{ es_hq_cont_name }}'
oauth_upstream_port: '{{ es_hq_cont_port }}'
oauth_public_port: 443
oauth_local_port: 8090
oauth_cookie_secret: '{{ lookup("bitwarden", "cookie-secret", field="secret") }}'
oauth_id: '{{ lookup("bitwarden", "the-hive/elasticSearch/oauth", field="id") }}'
oauth_secret: '{{ lookup("bitwarden", "the-hive/elasticSearch/oauth", field="secret") }}'

# Open Nginx Ports
open_ports_default_chain: 'VPN'
open_ports_list:
  - { port: 80,  chain: 'SERVICES', comment: 'ElasticSearchHQ' }
  - { port: 443, chain: 'SERVICES', comment: 'ElasticSearchHQ' }
  - { port: '{{ es_api_port }}',               ipset: 'thehive.prod', comment: 'ElasticSearch' }
  - { port: '{{ es_node_port }}',              ipset: 'thehive.prod', comment: 'ElasticSearch' }
  - { port: '{{ es_metrics_cont_port }}',      ipset: 'metrics.hq',   comment: 'ElasticSearch' }
  - { port: '{{ cassandra_storage_port }}',    ipset: 'thehive.prod', comment: 'Cassandra' }
  - { port: '{{ cassandra_native_port }}',     ipset: 'thehive.prod', comment: 'Cassandra' }
  - { port: '{{ cassandra_exp_listen_port }}', ipset: 'metrics.hq',   comment: 'Cassandra' }

# Proxy for ES HQ
nginx_sites:
  elasticsearch_hq_http:
    - listen 80
    - server_name {{ oauth_domain }}
    - return 302 https://$server_name$request_uri
  elasticsearch_hq_https:
    - listen 443 ssl
    - server_name {{ oauth_domain }}

    - ssl_certificate     /certs/status.im/origin.crt
    - ssl_certificate_key /certs/status.im/origin.key

    - location / {
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:{{ oauth_local_port }}/;
      }
