---
- name: nginx
  src: git@github.com:status-im/infra-role-nginx.git
  version: 3043c998cbc92a634a71dc48363b3e2525696d26
  scm: git

- name: origin-certs
  src: git@github.com:status-im/infra-role-origin-certs.git
  version: 60587f86e085255b537cc37647003af105214d20
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 7280600c2c6cf532fdbbbb31481fdb068dd0573e
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: b711bbabd2dc3d9ce8b1c3a6e5bc785901db9d09
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 7ee51839e6a032e6ca27dfb00951e897b5385609
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: 49c37e1df8feb4d7938b3cc2ffc59f6dfed10231
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  version: b1b60917e839f9205af3952574b1f2c893aaedba
  scm: git

- name: cassandra
  src: git@github.com:status-im/infra-role-cassandra.git
  version: df1d5ea174189095962ea46dc198eace4c5243e8
  scm: git

- name: elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  version: 18503666d0ec23b0f03328575531cd8ce8dce9db
  scm: git
