---
- name: nginx
  src: git@github.com:status-im/ansible-role-nginx.git
  scm: git

- name: origin-cert
  src: git@github.com:status-im/infra-role-origin-certs.git
  scm: git

- name: infra-role-tinc
  src: git@github.com:status-im/infra-role-tinc.git
  scm: git

- name: infra-role-bootstrap
  src: git@github.com:status-im/infra-role-bootstrap.git
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  scm: git

- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  scm: git

- name: oauth-proxy
  src: git@github.com:status-im/infra-role-oauth-proxy.git
  scm: git

- name: cassandra
  src: git@github.com:status-im/infra-role-cassandra.git
  scm: git

- name: elasticsearch
  src: git@github.com:status-im/infra-role-elasticsearch.git
  scm: git

- name: elasticsearch-hq
  src: git@github.com:status-im/infra-role-elasticsearch-hq.git
  scm: git
