---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ cortex_service_name }}'
    consul_services:
      # We prepend 'the-hive-' because there's already Cortex in infra-hq
      - name: 'the-hive-{{ cortex_service_name }}'
        tags: ['cortex', 'incidents', 'security']
        port: '{{ cortex_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        checks:
          - id: '{{ cortex_service_name }}-health'
            name: Cassandra Healthcheck
            type: http
            http: 'http://localhost:{{ cortex_port }}/'
