---
- name: Install Cortex
  import_tasks: install.yml

- name: Create config files
  import_tasks: config.yml

- name: Create Systemd service
  import_tasks: service.yml

- name: Create Consul definition
  import_tasks: consul.yml
