---
- name: Drop Docker configuration
  import_tasks: docker_fix.yml

- name: Install Cortex
  import_tasks: install.yml

- name: Create config files
  import_tasks: config.yml

- name: Create Systemd service
  import_tasks: service.yml

- name: Migrations and Super Admin
  import_tasks: setup.yml

- name: Create Org and users
  import_tasks: users.yml

- name: Create Consul definition
  import_tasks: consul.yml
